version: '2'
services:
  api:
    container_name: ibb-api-node
    build: .
    image: ibb-api:dev
    environment:
      PORT: 80
    ports:
      - "80:80"
  mysql:
    container_name: ibb-mysql-node
    image: "mysql:latest"
    volumes:
      - ./bin/mysql-config:/etc/mysql/conf.d
      - ~/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ibb