version: '2'
services:
  observer:
    container_name: ibb-observer-node
    build: .
    image: "wailorman/ibb-api:dev"
    command: bash -c "npm run observer && npm run observer:logs"
    environment:
      NODE_ENV: "production"
      DB_CONNECTION_STRING:
      OK_CREDENTIALS:
  api:
    container_name: ibb-api-node
    build: .
    image: "wailorman/ibb-api:dev"
    environment:
      PORT: 80
      DB_CONNECTION_STRING:
      OK_CREDENTIALS:
    ports:
      - "80:80"
  mysql:
    container_name: ibb-mysql-node
    image: "mysql:latest"
    volumes:
      - ./bin/mysql-config:/etc/mysql/conf.d
      - ~/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ibb