version: '2'
services:
  api:
    container_name: ibb-api-node
    build: .
    image: "wailorman/ibb-api"
    volumes:
      - ./ssl:/ibb/ssl
    restart: on-failure
    mem_limit: 400M
    command: npm run start
    environment:
      PORT: "443"
      NODE_ENV: "production"
      DB_CONNECTION_STRING:
      OK_CREDENTIALS:
    network_mode: "host"

  scrapper:
    extends: api
    container_name: ibb-scrapper-node
    mem_limit: 500M
    command: npm run scrapper
    environment:
      PARALLEL_HTTP_REQUESTS:
      FETCH_UNFILLED_INTERVAL:
      FETCH_CANDIDATES_INTERVAL:

  mem-observer:
    extends: scrapper
    container_name: ibb-mem-observer-node
    mem_limit: 300M
    command: npm run mem-observer
    environment:
      FETCH_MEMBERS_INTERVAL:

  mysql:
    container_name: ibb-mysql-node
    image: "mysql:5.7"
    volumes:
      - ./bin/mysql-config:/etc/mysql/conf.d
      - ~/db/data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: on-failure
    mem_limit: 1400M
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ibb