version: '2'
services:
  observer:
    container_name: ibb-observer-node
    build: .
    image: "wailorman/ibb-api"
    restart: on-failure
    mem_limit: 400M
    command: npm run observer
    environment:
      PARALLEL_HTTP_REQUESTS:
      FETCH_UNFILLED_INTERVAL:
      FETCH_FRESH_INTERVAL:
      FETCH_MEMBERS_INTERVAL:
      FETCH_CANDIDATES_INTERVAL:
      NODE_ENV: "production"
      DB_CONNECTION_STRING:
      OK_CREDENTIALS:
    ports:
      - "127.0.0.1:3306:3306"
  api:
    container_name: ibb-api-node
    build: .
    image: "wailorman/ibb-api"
    volumes:
      - ./ssl:/ibb/ssl
    restart: on-failure
    mem_limit: 400M
    command: npm run start
    environment:
      NODE_ENV: "production"
      DB_CONNECTION_STRING:
      OK_CREDENTIALS:
    ports:
      - "127.0.0.1:3306:3306"
      - "443:3000"
  mysql:
    container_name: ibb-mysql-node
    image: "mysql:5.7"

    volumes:
      - ./bin/mysql-config:/etc/mysql/conf.d
      - ~/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure
    mem_limit: 800M
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ibb