version: '2'
services:
  observer:
    container_name: ibb-observer-node
    build: .
    image: "wailorman/ibb-api"
    restart: on-failure
    mem_limit: 400M
    command: npm run observer && npm run observer:logs
    environment:
      NODE_ENV: "production"
      DB_CONNECTION_STRING:
      OK_CREDENTIALS:
  api:
    container_name: ibb-api-node
    build: .
    image: "wailorman/ibb-api"
    volumes:
      - ./ssl:/ibb/ssl
    restart: on-failure
    mem_limit: 400M
    command: npm run start
    environment:
      NODE_ENV: "production"
      DB_CONNECTION_STRING:
      OK_CREDENTIALS:
    ports:
      - "443:3000"
  mysql:
    container_name: ibb-mysql-node
    image: "mysql:5.7"

    volumes:
      - ./bin/mysql-config:/etc/mysql/conf.d
      - ~/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure
    mem_limit: 800M
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ibb