---

- name: Pull project
  vars:
    ansible_ssh_user: ibb
  hosts: all
  roles:
    - pull

- name: SSL
  hosts: app
  roles:
    - ssl

- name: Run containers
  vars:
    ansible_ssh_user: ibb
  hosts: all
  roles:
    - run
